AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'Gemfile.lock'
    - 'tmp/**/*'

Lint/EmptyClass:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
